import mongoose from 'mongoose';
import { env } from '../config/env.js';
import { logger } from '../config/logger.js';
import { User } from '../models/user.model.js';
import { WorkOrder } from '../models/work-order.model.js';
import { hashPassword } from '../utils/passwords.js';
import type { WorkOrderPriority, WorkOrderStatus } from '@workorders/shared';

interface TechSeed {
  name: string;
  email: string;
}

interface TicketSeed {
  title: string;
  description: string;
  priority: WorkOrderPriority;
  status: WorkOrderStatus;
  ownerEmail: string;
  ageHours: number;
  touchedHours: number;
  edits: number;
}

const TECHS: TechSeed[] = [
  { name: 'Marisol Vega', email: 'marisol@example.com' },
  { name: 'Dan Okafor', email: 'dan@example.com' },
  { name: 'Priya Nair', email: 'priya@example.com' },
  { name: 'Tom Becker', email: 'tom@example.com' },
  { name: 'Elena Ríos', email: 'elena@example.com' },
  { name: 'Marcus Lee', email: 'marcus@example.com' },
  { name: 'Jess Kim', email: 'jess@example.com' },
  { name: 'Omar Haddad', email: 'omar@example.com' },
  { name: 'Grace Lin', email: 'grace@example.com' },
];

const TICKETS: TicketSeed[] = [
  // ── High priority ──────────────────────────────────────────────────────────
  {
    title: 'Burst pipe — Unit 12 kitchen',
    description: 'Call from tenant at 07:40, water pouring through ceiling into kitchen below.\nIsolated supply to Unit 12, cut drywall to access, replaced 6ft of copper, sweat joints, pressure tested. Unit dried out, but ceiling drywall still needs patch.',
    priority: 'high',
    status: 'in_progress',
    ownerEmail: 'dan@example.com',
    ageHours: 9,
    touchedHours: 1,
    edits: 2,
  },
  {
    title: 'Rooftop AC compressor won’t start',
    description: 'RTU-3 dead on arrival of service call. Capacitor bulged, amp draw on start winding 0.\nReplaced start capacitor (55/7.5 uF), contactor, and run cap. System pulls 18A, cooling OK. Ordered thermal expansion valve for follow-up.',
    priority: 'high',
    status: 'in_progress',
    ownerEmail: 'marisol@example.com',
    ageHours: 26,
    touchedHours: 2,
    edits: 3,
  },
  {
    title: 'Gas smell near water heater — Apt 7C',
    description: 'Tenant reported gas odor. Soap-tested all fittings on WH and riser — leak found on union at cold inlet.\nReplaced union, re-threaded with dope, tested with soap again. Called gas co. for meter recheck. Unit safe, door tagged.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 30,
    touchedHours: 4,
    edits: 3,
  },
  {
    title: 'Main breaker tripping — Retail Suite 200',
    description: 'Trips under ~40A load, panel warm to touch. Terminals on main lug discolored, torque checked.\nCleaned bus, replaced main breaker 100A, re-torqued lugs to spec. Advised owner about growing load — recommend subpanel.',
    priority: 'high',
    status: 'pending',
    ownerEmail: 'elena@example.com',
    ageHours: 4,
    touchedHours: 4,
    edits: 0,
  },
  {
    title: 'Elevator stuck between floors — Bldg C',
    description: 'Elevator halted between L2 and L3, passenger evacuated by FD. Hydraulic unit low on fluid.\nTopped fluid, cycled car, checked limit switches. Referred to licensed elevator vendor — outside scope.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 76,
    touchedHours: 30,
    edits: 4,
  },
  // ── In progress / medium ───────────────────────────────────────────────────
  {
    title: 'Replace condensate pump — AC unit Rooftop 3',
    description: 'Pump failed, water pooled in drain pan and dripped onto ceiling tiles in hallway.\nRemoved old Little Giant pump, installed VCMA-20 with overflow shutoff. Primed and tested with fill valve. Tiles to be replaced by maintenance.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'priya@example.com',
    ageHours: 20,
    touchedHours: 3,
    edits: 2,
  },
  {
    title: 'Unclog main drain line — Apt 4B',
    description: 'Bathroom sink and tub backing up, slow drains throughout unit.\nRan 50ft auger from cleanout, pulled hair and scale. Snaked main stack to roof vent. Drained fully. Recommend annual hydro-jetting.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'dan@example.com',
    ageHours: 50,
    touchedHours: 6,
    edits: 2,
  },
  {
    title: 'Diagnose flickering lights — Lobby',
    description: 'Flicker on the 2nd and 3rd fixture circuits, worse when elevator runs.\nMeasured phase-to-phase balance, found loose neutral on shared panel. Retorqued neutral bar, tightened fixture connections. No flicker on test.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'elena@example.com',
    ageHours: 44,
    touchedHours: 5,
    edits: 3,
  },
  {
    title: 'Install smart thermostat — Unit 1202',
    description: 'Swap old programmable stat for Nest. Checked C-wire present at stat location.\nInstalled, wired Rc/Rh/C, set up on WiFi, verified heat/cool call from app. Showed tenant how to set schedule.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marisol@example.com',
    ageHours: 90,
    touchedHours: 22,
    edits: 1,
  },
  {
    title: 'HVAC blower motor noisy — Suite 300',
    description: 'Rattling and grinding from AHU blower, wheel wobbles on shaft.\nReplaced blower motor + wheel assembly, balanced, amp draw 4.6A within spec. Filter changed while in the unit.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'priya@example.com',
    ageHours: 8,
    touchedHours: 8,
    edits: 0,
  },
  {
    title: 'Water heater pilot light out — Unit 7C',
    description: 'No hot water, thermocouple worn. Replaced thermocouple, purged line, relit pilot.\nSet temp to 120°F. Tank at 80% — recommend replacement within 6 months.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 120,
    touchedHours: 48,
    edits: 2,
  },
  {
    title: 'Fix leaking faucet — Break room',
    description: 'Kitchen faucet drips at spout base and handle is stiff. Replaced cartridge and o-rings, greased stem.\nNo drip after 15 min soak test. Handed building key back to front desk.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 150,
    touchedHours: 100,
    edits: 1,
  },
  {
    title: 'Rewire GFCI — Laundry room',
    description: 'GFCI outlet dead, tester shows open ground. Daisy-chained circuit downstream lost power.\nReplaced GFCI, corrected load/line wiring, verified ground at box. All 4 outlets downstream tested OK.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'elena@example.com',
    ageHours: 16,
    touchedHours: 6,
    edits: 2,
  },
  {
    title: 'Seal window draft — Unit 3A',
    description: 'Cold draft around 3rd-floor bedroom window all winter. Caulk dry and gasket shrunk.\nRemoved old caulk, applied exterior sealant, replaced compression gasket. Reported savings estimate to tenant.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 200,
    touchedHours: 170,
    edits: 1,
  },
  // ── Pending / general ──────────────────────────────────────────────────────
  {
    title: 'Refrigerator not cooling — Commercial kitchen',
    description: 'Walk-in fridge holding 55°F, evap coil iced over. Defrost heater continuity suspect.\nOrdered defrost heater and thermostat kit. Scheduled follow-up for Wednesday AM.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'priya@example.com',
    ageHours: 12,
    touchedHours: 12,
    edits: 1,
  },
  {
    title: 'Replace air filters — Rooftop units 1–4',
    description: 'Quarterly PM. Pulled old 20x25x4 MERV-8, replaced all four, noted pressure drop 0.4" w.c. after install.\nBelt tension checked, drains flushed. Logged next PM date.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marisol@example.com',
    ageHours: 300,
    touchedHours: 280,
    edits: 2,
  },
  {
    title: 'Pressure test gas line — New build',
    description: 'Rough-in complete, line to hold 15 psi for 30 min.\nTest held at 14.9 psi with zero drop. Tagged and logged. Ready for appliance hookup inspection.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 55,
    touchedHours: 20,
    edits: 2,
  },
  {
    title: 'Sump pump cycling — Basement B2',
    description: 'Pump runs every 3 minutes, water table high after rains. Float switch sticking.\nCleaned float guide, replaced check valve. Timer set. Will monitor for 48h.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'dan@example.com',
    ageHours: 33,
    touchedHours: 8,
    edits: 2,
  },
  {
    title: 'Clean dryer vent — Laundry room',
    description: 'Vent clogged with lint, dryer takes 2+ cycles to dry. Disconnected, brushed full run to roof, 40ft.\nReinstalled, airflow measured with hood tester. Dryer now dries in one cycle.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 260,
    touchedHours: 230,
    edits: 1,
  },
  {
    title: 'Broken lock on service door',
    description: 'Key turns but deadbolt does not throw. Mortise mechanism worn out.\nReplaced deadbolt assembly, re-keyed to master. Tested from both sides.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 180,
    touchedHours: 150,
    edits: 1,
  },
  {
    title: 'Wi-Fi thermostat offline — Unit 904',
    description: 'Tenant’s thermostat drops off WiFi daily. Access point signal weak at unit.\nRebooted thermostat, reseated C-wire, moved hub 6ft closer. Signal now -58 dBm. Monitored 24h.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'marisol@example.com',
    ageHours: 15,
    touchedHours: 15,
    edits: 0,
  },
  {
    title: 'Pressure washer service — Loading dock',
    description: 'Unit surges and sputters at throttle. Carburetor gummed from winter storage.\nCleaned carb, replaced fuel lines and filter, changed oil. Idles smooth, 2800 psi at wand.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 140,
    touchedHours: 110,
    edits: 1,
  },
  {
    title: 'Roof patch — Leak over Lobby',
    description: 'Water stain on lobby ceiling after heavy rain. Found cracked flashing around vent pipe.\nCleaned, applied self-adhered membrane + sealant over flashing. Interior patch scheduled.',
    priority: 'high',
    status: 'pending',
    ownerEmail: 'dan@example.com',
    ageHours: 3,
    touchedHours: 3,
    edits: 0,
  },
  {
    title: 'Door closer adjustment — Front entrance',
    description: 'Door slams shut, closer too fast. Adjusted sweep and latch speed, lubricated pivot.\nDoor now closes in ~5s. Checked hold-open release.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 90,
    touchedHours: 70,
    edits: 1,
  },
  {
    title: 'Install exhaust fan — Unit 505 bathroom',
    description: 'No ventilation in bathroom, mold on ceiling corners. New Panasonic fan + duct run to roof.\nRough-in done, fan installed on GFCI circuit, duct insulated. Balanced at 90 CFM.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'elena@example.com',
    ageHours: 40,
    touchedHours: 12,
    edits: 3,
  },
  {
    title: 'Termite inspection — Bldg B crawl space',
    description: 'Annual inspection. Evidence of old activity at sill plate, no active tubes found.\nTreated 3ft band along affected sill. Documented photos for records.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'priya@example.com',
    ageHours: 400,
    touchedHours: 390,
    edits: 1,
  },
  {
    title: 'Pool pump motor seized — Rec center',
    description: 'Motor hums and trips breaker. Shaft seized, bearings rusted.\nReplaced 1.5HP pump motor, primed, verified flow. Skimmer baskets cleaned.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'dan@example.com',
    ageHours: 7,
    touchedHours: 7,
    edits: 0,
  },
  {
    title: 'Heat pump defrost cycle — Suite 410',
    description: 'Unit iced over during cold snap, defrost board not cycling. Thermistor reading off.\nReplaced defrost thermistor and control board. Ran two defrost cycles manually, unit clear.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'marisol@example.com',
    ageHours: 100,
    touchedHours: 60,
    edits: 2,
  },
  {
    title: 'Replace toilet flapper — Unit 2C',
    description: 'Toilet runs constantly, flapper perished. Replaced flapper + fill valve, adjusted level.\nWater use dropped. Tenant happy.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 220,
    touchedHours: 200,
    edits: 1,
  },
  {
    title: 'Exterior lighting — Parking lot pole 4',
    description: 'Pole 4 dark, photocell likely failed. Replaced photocell and ballast.\nFixture on at dusk, off at dawn. Logged lamp hours.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'elena@example.com',
    ageHours: 300,
    touchedHours: 280,
    edits: 1,
  },
  {
    title: 'Boiler low-water cutoff test — Mechanical room',
    description: 'Monthly boiler inspection. LWCO function tested, sight glass cleaned.\nBlowdown performed, water level corrected. All safeties verified.',
    priority: 'high',
    status: 'in_progress',
    ownerEmail: 'marcus@example.com',
    ageHours: 30,
    touchedHours: 10,
    edits: 2,
  },
  {
    title: 'Fire alarm horn strobe — Unit 618',
    description: 'Strobe not flashing during weekly test. Replaced horn/strobe, verified on 24VDC loop.\nSupervision restored, panel reset.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'priya@example.com',
    ageHours: 2,
    touchedHours: 2,
    edits: 0,
  },
];

const EXTRA_TICKETS: TicketSeed[] = [
  // ── Hot / today ────────────────────────────────────────────────────────────
  {
    title: 'Tenant locked out — Unit 11A',
    description: 'Lockout at 08:10, tenant standing in hallway. Re-keyed unit deadbolt on the spot, verified key turn.\nLogged master key check-out and return.',
    priority: 'high',
    status: 'pending',
    ownerEmail: 'jess@example.com',
    ageHours: 1,
    touchedHours: 1,
    edits: 0,
  },
  {
    title: 'Garage door won’t close — Bldg D',
    description: 'Door reverses at halfway, safety beam misaligned after truck hit the frame.\nRealigned photo-eyes, adjusted travel limit, tested full cycle 5x. Slight dent noted on bottom panel.',
    priority: 'high',
    status: 'in_progress',
    ownerEmail: 'omar@example.com',
    ageHours: 5,
    touchedHours: 2,
    edits: 1,
  },
  {
    title: 'No hot water — Units 300–320 riser',
    description: 'Riser group has lukewarm water, recirc pump dead in mechanical room.\nReplaced circulator pump and check valve, bled the loop. Temp back to 128°F at far riser.',
    priority: 'high',
    status: 'pending',
    ownerEmail: 'marcus@example.com',
    ageHours: 6,
    touchedHours: 6,
    edits: 0,
  },
  {
    title: 'Kitchen drain overflowing — Unit 6E',
    description: 'Sink backs up within minutes of running water. Food waste + grease clog in branch line.\nAugered 25ft, hot-flushed with degreaser. Drains freely now. Tenant advised on grease disposal.',
    priority: 'medium',
    status: 'pending',
    ownerEmail: 'dan@example.com',
    ageHours: 3,
    touchedHours: 3,
    edits: 0,
  },
  {
    title: 'Dishwasher leaking — Unit 2F',
    description: 'Water on floor under dishwasher during rinse cycle. Door gasket split at bottom corner.\nReplaced gasket, cleaned pump screen, ran two rinse cycles. Leak resolved.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 24,
    touchedHours: 6,
    edits: 2,
  },
  {
    title: 'Exterior door won’t latch — Main entrance',
    description: 'Latch misses strike plate, door sags on hinge. Re-hung door, replaced hinges and strike.\nLatch throws clean, door self-closes. Adjusted closer tension.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'jess@example.com',
    ageHours: 40,
    touchedHours: 18,
    edits: 1,
  },
  // ── This week ──────────────────────────────────────────────────────────────
  {
    title: 'Water heater rusted pan — Unit 5G',
    description: 'Pan rusted through, slow leak to unit below. Replaced pan, insulated lines, added leak alarm.\nScheduled tank swap for next quarter.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 70,
    touchedHours: 30,
    edits: 2,
  },
  {
    title: 'Drywall patch — Lobby ceiling',
    description: 'Water stain and hole from prior roof leak. Cut out stained board, patched, textured, painted.\nMatched lobby ceiling paint. Sealed and primed first.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'omar@example.com',
    ageHours: 80,
    touchedHours: 26,
    edits: 2,
  },
  {
    title: 'Ice maker not making ice — Clubhouse',
    description: 'Ice maker iced over, mold inside bin. Defrosted, cleaned line and bin, replaced filter.\nMaking ice again. Advised monthly bin clean.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 95,
    touchedHours: 50,
    edits: 1,
  },
  {
    title: 'Garbage disposal jammed — Unit 8C',
    description: 'Disposal hums but won’t spin. Allen key freed jam, cleared rotor plate, reset breaker.\nTested with cold water and citrus. Fine.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'dan@example.com',
    ageHours: 110,
    touchedHours: 70,
    edits: 1,
  },
  {
    title: 'Security camera offline — Parking level 2',
    description: 'Cam 7 black. PoE injector dead at switch. Replaced injector, reseated cable, cam online.\nTime synced, recording verified.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'elena@example.com',
    ageHours: 130,
    touchedHours: 60,
    edits: 1,
  },
  {
    title: 'Stairwell lights flickering — Bldg A',
    description: 'Third floor stairwell strobes. Bad ballast on one fixture. Replaced ballast + lamps.\nWhole run steady. Logged lamp change.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'elena@example.com',
    ageHours: 140,
    touchedHours: 90,
    edits: 1,
  },
  {
    title: 'Leaky roof valley — Bldg B',
    description: 'Rain drip at interior valley. Shingles lifted, flashing nail pop. Re-sealed flashing, replaced 3 shingles.\nNo leak after storm soak. Monitored 48h.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'omar@example.com',
    ageHours: 160,
    touchedHours: 70,
    edits: 3,
  },
  {
    title: 'A/C condensate drain clogged — Suite 205',
    description: 'Water dripping from ceiling register. Slime in drain line. Vacuumed line, poured pan tabs.\nDrain clear, no leak after cycle. Added cleanout fitting for future.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'priya@example.com',
    ageHours: 170,
    touchedHours: 100,
    edits: 2,
  },
  {
    title: 'Broken toilet seat — Men’s restroom',
    description: 'Seat cracked, hinge rusted. Replaced seat + hinges, tightened to bowl.\nGood as new.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 190,
    touchedHours: 150,
    edits: 0,
  },
  // ── Last two weeks ─────────────────────────────────────────────────────────
  {
    title: 'Boiler pressure drop — Mechanical room',
    description: 'System losing 5 psi/night. Found leaking relief valve and two air vents. Replaced parts, purged air.\nPressure steady at 14 psi for 3 days.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 230,
    touchedHours: 120,
    edits: 3,
  },
  {
    title: 'Sprinkler head replaced — Parking deck',
    description: 'Head corroded, weeping. Cut, replaced, hydro-tested zone.\nNo leaks. Tagged for inspection.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 250,
    touchedHours: 130,
    edits: 1,
  },
  {
    title: 'Washer drain pan flooded — Laundry 4',
    description: 'Standpipe overflow during spin. Vent clogged with lint. Cleaned vent stack, flushed drain.\nMachine cycles full without overflow.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 280,
    touchedHours: 160,
    edits: 1,
  },
  {
    title: 'Elevator door sensor — Car B',
    description: 'Doors reopen mid-close, sensor misaligned after cleaning crew bumped header.\nRealigned IR sensors, tested 20 cycles. Smooth.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'jess@example.com',
    ageHours: 300,
    touchedHours: 200,
    edits: 2,
  },
  {
    title: 'Paint touch-up — Hallway level 4',
    description: 'Scuffed walls around elevator doors and corners. Matched paint, feathered edges.\nSpot touch-up done, no masking lines.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'omar@example.com',
    ageHours: 320,
    touchedHours: 240,
    edits: 0,
  },
  {
    title: 'Window screen repair — Unit 12D',
    description: 'Screen torn, frame bent. Replaced screen mesh, straightened frame.\nFits snug, no gaps.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 340,
    touchedHours: 290,
    edits: 0,
  },
  {
    title: 'Smoke detector beeping — Unit 9B',
    description: 'Low battery chirp overnight. Replaced 9V in three detectors, tested all.\nSilent. Logged battery replacement dates.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'jess@example.com',
    ageHours: 360,
    touchedHours: 330,
    edits: 0,
  },
  {
    title: 'Water pressure low — Unit 4D',
    description: '40 psi at unit, neighbor complains too. Clogged strainer on PRV. Cleaned strainer, set PRV to 55 psi.\nPressure steady at all taps.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'dan@example.com',
    ageHours: 400,
    touchedHours: 250,
    edits: 2,
  },
  // ── Last month ─────────────────────────────────────────────────────────────
  {
    title: 'Tune-up package AC — 88 Maple St',
    description: 'Seasonal tune-up: cleaned coils, checked charge, replaced filter, lubed fan motor.\nSuction 68 psi / head 245 psi, delta T 19°F. Unit running clean.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'marisol@example.com',
    ageHours: 500,
    touchedHours: 300,
    edits: 2,
  },
  {
    title: 'Hot water recirc timer — Bldg C',
    description: 'Recirc pump runs 24/7, wasting heat. Installed programmable timer, set to occupancy schedule.\nEstimated 18% gas savings. Tenant thanks on door note.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'marcus@example.com',
    ageHours: 520,
    touchedHours: 360,
    edits: 1,
  },
  {
    title: 'Exterior hose bib — Unit 1C',
    description: 'Bib leaks at handle, froze last winter. Replaced anti-siphon bib, insulated cover.\nNo drip, frost-proof for winter.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'tom@example.com',
    ageHours: 560,
    touchedHours: 430,
    edits: 0,
  },
  {
    title: 'Bed bugs heat treatment — Unit 3F',
    description: 'Confirmed bed bugs in bedroom. Whole-unit heat treatment 135°F for 6h, furniture spaced.\nRe-inspection in 2 weeks scheduled. Tenant checklist given.',
    priority: 'high',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 600,
    touchedHours: 380,
    edits: 4,
  },
  {
    title: 'Pest control — Ants in lobby',
    description: 'Ant trail along lobby baseboard from planter. Bait stations placed, gaps sealed.\nNo activity after 5 days. Monthly service noted.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'omar@example.com',
    ageHours: 650,
    touchedHours: 540,
    edits: 0,
  },
  {
    title: 'Parking gate arm — Exit 2',
    description: 'Arm falls when open. Spring tension worn. Adjusted spring, replaced rubber edge strip.\nGate holds open, closes on timer.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'elena@example.com',
    ageHours: 700,
    touchedHours: 600,
    edits: 1,
  },
  {
    title: 'Roof inspection — Spring walk',
    description: 'Full roof walk after winter. Two nail pops, one lifting tab. Reset and sealed all.\nReport filed, photos attached. Recommend recoating in 2 years.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'omar@example.com',
    ageHours: 760,
    touchedHours: 700,
    edits: 1,
  },
  {
    title: 'Security gate — Front drive',
    description: 'Gate motor armature worn, gate drifts. Replaced limit switch and lubricated track.\nGate cycles clean, auto-close on.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'jess@example.com',
    ageHours: 800,
    touchedHours: 720,
    edits: 1,
  },
  {
    title: 'Unit 4A — Keyed fob not working',
    description: 'Fob dead after battery swap. Reprogrammed fob to reader, synced schedule.\nWorks at all 3 doors.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'grace@example.com',
    ageHours: 850,
    touchedHours: 800,
    edits: 0,
  },
  {
    title: 'Seasonal: flush AC lineset — Bldg B',
    description: 'Pre-season flush of rooftop units. Nitrogen flush, checked filters, tightened access panels.\nAll 6 units logged ready for summer.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'marisol@example.com',
    ageHours: 880,
    touchedHours: 820,
    edits: 2,
  },
  {
    title: 'Replace mail slot — Lobby',
    description: 'Slot rusted, envelope catch broken. Replaced slot, re-secured to door.\nLetters drop clean, flap closes.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'jess@example.com',
    ageHours: 910,
    touchedHours: 880,
    edits: 0,
  },
  // ── Seed user’s own route ──────────────────────────────────────────────────
  {
    title: 'Inspect unit turnover — 7B (move-in)',
    description: 'Turnover inspection before new tenant: tested appliances, fixtures, locks, thermostat.\nAll pass. Paint touch-up noted on kitchen island. Ready for showing.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'user@example.com',
    ageHours: 14,
    touchedHours: 4,
    edits: 1,
  },
  {
    title: 'Leaky shower head — Unit 10A',
    description: 'Drip at shower head arm. Tape seal worn. Re-threaded with tape, replaced washer.\nDry after 30 min test.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'user@example.com',
    ageHours: 45,
    touchedHours: 20,
    edits: 1,
  },
  {
    title: 'Cabinet hinge snapped — Unit 5F kitchen',
    description: 'Hinge broke, door hanging. Replaced hinge, adjusted alignment.\nDoor closes flush.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'user@example.com',
    ageHours: 90,
    touchedHours: 70,
    edits: 0,
  },
  {
    title: 'Bathtub caulk failing — Unit 8F',
    description: 'Caulk cracked, mold at tub edge. Scraped, cleaned, re-caulked with silicone.\nCured 24h, sealed tight.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'user@example.com',
    ageHours: 150,
    touchedHours: 130,
    edits: 0,
  },
  {
    title: 'Ceiling fan wobbles — Unit 12C',
    description: 'Fan shakes at high speed. Blade bracket loose. Tightened bracket, balanced blades.\nSilent on all speeds.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'user@example.com',
    ageHours: 220,
    touchedHours: 190,
    edits: 0,
  },
  {
    title: 'Closet shelf collapse — Unit 3G',
    description: 'Shelf anchors pulled from drywall. Installed toggle anchors + new brackets.\nLoaded test with boxes, solid.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'user@example.com',
    ageHours: 300,
    touchedHours: 270,
    edits: 0,
  },
  // ── Admin / dispatcher’s own route ─────────────────────────────────────────
  {
    title: 'Quarterly safety walk — Lobby and corridors',
    description: 'Walked L1–L4 common areas. Checked egress lighting, exit signs, handrails, door closers.\nTwo exit-sign lamps dim; replacement scheduled. Minor scuff marks noted for paint.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'admin@example.com',
    ageHours: 8,
    touchedHours: 2,
    edits: 2,
  },
  {
    title: 'Punch list — Unit 7B move-in',
    description: 'Verified turnover items before tenant move-in: fixtures, locks, thermostat, appliances.\nOne kitchen outlet cover missing; replaced on the spot. Unit cleared for move-in.',
    priority: 'medium',
    status: 'done',
    ownerEmail: 'admin@example.com',
    ageHours: 30,
    touchedHours: 6,
    edits: 2,
  },
  {
    title: 'Compliance check — Fire extinguishers L1–L3',
    description: 'Monthly inspection of extinguishers on all three levels. Checked pressure, seals, tags.\nAll serviceable. Two tags near expiry, renewal logged with vendor.',
    priority: 'high',
    status: 'pending',
    ownerEmail: 'admin@example.com',
    ageHours: 3,
    touchedHours: 3,
    edits: 0,
  },
  {
    title: 'Owner walkthrough — Rooftop deck',
    description: 'Accompanied owner on the deck, documented wear on membrane seams and a rusted railing bolt.\nLogged both items for the maintenance queue. Deck remains accessible.',
    priority: 'low',
    status: 'done',
    ownerEmail: 'admin@example.com',
    ageHours: 60,
    touchedHours: 40,
    edits: 1,
  },
  {
    title: 'Stock room inventory audit',
    description: 'Quarterly parts count: filters, cartridges, lamps, plumbing and electrical spares.\nReorder list generated for low-stock items. Discrepancies logged for review.',
    priority: 'low',
    status: 'pending',
    ownerEmail: 'admin@example.com',
    ageHours: 12,
    touchedHours: 12,
    edits: 0,
  },
  {
    title: 'Warranty claim — Rooftop AC compressor',
    description: 'Compressor failed outside spec, manufacturer warranty active. Documented serial, fault code, photos.\nClaim submitted, replacement unit ordered. Follow-up scheduled for delivery.',
    priority: 'medium',
    status: 'in_progress',
    ownerEmail: 'admin@example.com',
    ageHours: 50,
    touchedHours: 24,
    edits: 3,
  },
];

async function upsertTech(seed: TechSeed): Promise<string> {
  let user = await User.findOne({ email: seed.email });
  if (!user) {
    user = await User.create({
      email: seed.email,
      name: seed.name,
      passwordHash: await hashPassword('TechPass123'),
      role: 'user',
      isActive: true,
    });
    logger.info({ email: seed.email }, 'seeded technician');
  }
  return user._id.toString();
}

async function main(): Promise<void> {
  await mongoose.connect(env.MONGODB_URI);
  logger.info('seed-demo: connected');

  const ownerIds = new Map<string, string>();
  for (const tech of TECHS) {
    ownerIds.set(tech.email, await upsertTech(tech));
  }
  const baseUser = await User.findOne({ email: env.SEED_USER_EMAIL });
  if (baseUser) ownerIds.set(baseUser.email, baseUser._id.toString());
  const adminUser = await User.findOne({ email: env.SEED_ADMIN_EMAIL });
  if (adminUser) ownerIds.set(adminUser.email, adminUser._id.toString());

  let created = 0;
  const allTickets = [...TICKETS, ...EXTRA_TICKETS];
  for (const ticket of allTickets) {
    const exists = await WorkOrder.findOne({ title: ticket.title });
    if (exists) continue;
    const ownerId = ownerIds.get(ticket.ownerEmail);
    if (!ownerId) continue;
    const now = Date.now();
    const createdAt = new Date(now - ticket.ageHours * 3600 * 1000);
    const updatedAt = new Date(now - ticket.touchedHours * 3600 * 1000);
    await WorkOrder.create({
      title: ticket.title,
      description: ticket.description,
      priority: ticket.priority,
      status: ticket.status,
      owner: ownerId,
      version: ticket.edits + 1,
      createdAt,
      updatedAt,
    });
    created += 1;
  }

  logger.info({ created, total: allTickets.length }, 'seed-demo: complete');
  await mongoose.disconnect();
}

main().catch((err) => {
  logger.error({ err }, 'seed-demo failed');
  process.exit(1);
});